accumulating_gradients: true
amp_opt_level: 1
assume_yes: false
base_lr: 0.05
batch_size: 2
bn_flag: true
checkpoint: null
clip: false
clip_grad_norm: 0.5
complete: true
config: ./config/nturgbd-cross-subject/train_joint.yaml
data_dir: null
data_mirroring: false
debug: false
device:
- 0
display_by_category: false
display_recall_precision: false
eval_interval: 1
eval_start: 1
exp_name: prova20
feeder: feeders.feeder.Feeder
feeder_augmented: feeder.feeder_augmented
forward_batch_size: 1
gcn0_flag: false
half: false
ignore_weights: []
local_rank: 0
log_dir: null
log_interval: 100
model: model.msg3d.Model
model_args:
  Nh: 8
  adjacency: false
  agcn: false
  all_layers: false
  attention: true
  attention_3: false
  bn_flag: true
  channel: 6
  concat_original: true
  data_normalization: true
  device:
  - 0
  dim_block1: 10
  dim_block2: 30
  dim_block3: 75
  dk: 0.25
  double_channel: true
  drop_connect: true
  dv: 0.25
  graph: graph.ntu_rgb_d.AdjMatrixGraph
  kernel_temporal: 9
  mask_learning: true
  more_channels: false
  n: 4
  num_class: 60
  num_g3d_scales: 1
  num_gcn_scales: 13
  num_person: 2
  num_point: 25
  only_attention: true
  only_temporal_attention: true
  relative: false
  skip_conn: true
  tcn_attention: false
  use_data_bn: true
  visualization: false
  weight_matrix: 2
model_saved_name: ''
nesterov: true
num_epoch: 50
num_worker: 12
optimize_every: 2
optimizer: SGD
optimizer_states: null
phase: train
print_log: true
save_interval: 1
save_score: false
scheduler: 1
scheduling_lr: true
seed: 11
show_topk:
- 1
- 5
start_epoch: 0
step:
- 30
- 40
test_batch_size: 2
test_feeder_args:
  data_path: /media/curtisle/DATA/Documents/Projects/CCU/Code/CCU_Project/MS_G3D/data/ntu/xsub/val_data_joint.npy
  label_path: /media/curtisle/DATA/Documents/Projects/CCU/Code/CCU_Project/MS_G3D/data/ntu/xsub/val_label.pkl
test_feeder_args_new: {}
train_feeder_args:
  data_path: /media/curtisle/DATA/Documents/Projects/CCU/Code/CCU_Project/MS_G3D/data/ntu/xsub/train_data_joint.npy
  debug: false
  label_path: /media/curtisle/DATA/Documents/Projects/CCU/Code/CCU_Project/MS_G3D/data/ntu/xsub/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
train_feeder_args_new: {}
training: true
val_split: 0.2
validation_split: false
weight_decay: 0.0005
weights: null
work_dir: ./word_dir/train_temporal/CS
writer_enabled: true
