amp_opt_level: 1
assume_yes: false
base_lr: 0.05
batch_size: 8
checkpoint: null
config: ./config/nturgbd-cross-subject/train_joint.yaml
debug: false
device:
- 0
eval_interval: 1
eval_start: 1
feeder: feeders.feeder.Feeder
forward_batch_size: 4
half: false
ignore_weights: []
log_interval: 100
model: model.msg3d.Model
model_args:
  graph: graph.ntu_rgb_d.AdjMatrixGraph
  num_class: 60
  num_g3d_scales: 6
  num_gcn_scales: 13
  num_person: 2
  num_point: 25
model_saved_name: ''
nesterov: true
num_epoch: 50
num_worker: 12
optimizer: SGD
optimizer_states: null
phase: train
print_log: true
save_interval: 1
save_score: false
seed: 30
show_topk:
- 1
- 5
start_epoch: 0
step:
- 30
- 40
test_batch_size: 8
test_feeder_args:
  data_path: /media/curtisle/DATA/Documents/Projects/CCU/Code/CCU_Project/MS_G3D/data/ntu/xsub/val_data_joint.npy
  label_path: /media/curtisle/DATA/Documents/Projects/CCU/Code/CCU_Project/MS_G3D/data/ntu/xsub/val_label.pkl
train_feeder_args:
  data_path: /media/curtisle/DATA/Documents/Projects/CCU/Code/CCU_Project/MS_G3D/data/ntu/xsub/train_data_joint.npy
  debug: false
  label_path: /media/curtisle/DATA/Documents/Projects/CCU/Code/CCU_Project/MS_G3D/data/ntu/xsub/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
weight_decay: 0.0005
weights: null
work_dir: ./word_dir/train_temporal/CS
