
work_dir: ./word_dir/train_temporal/CS

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /media/curtisle/DATA/Documents/Projects/CCU/Code/CCU_Project/MS_G3D/data/ntu/xsub/train_data_joint.npy
  label_path: /media/curtisle/DATA/Documents/Projects/CCU/Code/CCU_Project/MS_G3D/data/ntu/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /media/curtisle/DATA/Documents/Projects/CCU/Code/CCU_Project/MS_G3D/data/ntu/xsub/val_data_joint.npy
  label_path: /media/curtisle/DATA/Documents/Projects/CCU/Code/CCU_Project/MS_G3D/data/ntu/xsub/val_label.pkl

##Original Code Begin
# model
# model: model.msg3d.Model
# model_args:
#   num_class: 60
#   num_point: 25
#   num_person: 2
#   num_gcn_scales: 13    # `num_scales` == `K + 1` in the paper
#   num_g3d_scales: 6
#   graph: graph.ntu_rgb_d.AdjMatrixGraph
##Original Code End


##Edit Code Begin 12
model: model.msg3d.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  num_gcn_scales: 13    
  num_g3d_scales: 1
  channel: 6
  mask_learning: True
  use_data_bn: True
  attention: True
  only_attention: True
  tcn_attention: False
  data_normalization: True
  skip_conn: True
  weight_matrix: 2
  only_temporal_attention: True
  bn_flag: True
  attention_3: False
  kernel_temporal: 9
  more_channels: False
  double_channel: True
  drop_connect: True
  concat_original: True
  all_layers: False
  adjacency: False
  agcn: False
  dv: 0.25
  dk: 0.25
  Nh: 8
  n: 4
  dim_block1: 10
  dim_block2: 30
  dim_block3: 75
  device: [0]
  relative: False
  visualization: False
  graph: graph.ntu_rgb_d.AdjMatrixGraph
  # graph_args:
  #   labeling_mode: 'spatial'
##Edit Code End 12


# optim
scheduler: 1

weight_decay: 0.0005
base_lr: 0.05
step: [30, 40]

# training
num_epoch: 50
device: [0]
batch_size: 2
forward_batch_size: 1
test_batch_size: 2
nesterov: True

